/**
 * all validations in milliseconds
 */
export enum TokenValidity {
  ONE_DAY = 24 * 60 * 60 * 1000,
  TEN_MINUTES = 10 * 60 * 1000,
  ONE_HOUR = 60 * 60 * 1000,
}

export enum TokenErrors {
  ACCESS_TOKEN_EXPIRED = "ACCESS_TOKEN_EXPIRED",
  ACCESS_TOKEN_INVALID = "ACCESS_TOKEN_INVALID",
  ACCESS_TOKEN_MISSING = "ACCESS_TOKEN_MISSING",
  REFRESH_TOKEN_EXPIRED = "REFRESH_TOKEN_EXPIRED",
  REFRESH_TOKEN_INVALID = "REFRESH_TOKEN_INVALID",
}
